### PR TITLE
Support subclass positions

### PR DESCRIPTION
**Pull request by gbp**
Extracted from #25 
Requires #27 
Requires #29
Required for mysociety/verification-pages#314

Need to pass in an array of `position_children` with the suggestion for this to work.

### CODE REVIEW

**Review by chrismytton — APPROVED** [review]
👍

**Comment by gbp** [comment]
@tmtmtmtm this is the result to extracting commits from #25 - do you want to take a look and review?

**Comment by tmtmtmtm** [comment]
@gbp As mentioned before I think using the Speaker as a subclass to be quite misleading and more difficult to reason about than it should be, and I fear that it will cause problems down the line if people think that this is about that sort of position, and not the term-specific membership items.

**Comment by gbp** [comment]
> @gbp As mentioned before I think using the Speaker as a subclass to be quite misleading and more difficult to reason about than it should be, and I fear that it will cause problems down the line if people think that this is about that sort of position, and not the term-specific membership items.

Ah yes, I've switched to a UK term specific position in fixup b486a27. Also changed the term/party/district to UK ones so we're not mixing UK/CA items in the examples.

**Comment by tmtmtmtm** [comment]
@gbp: great. I think mainly we need to just get these live enough to properly test with real data.

**Comment by gbp** [comment]
Merged 41c79e81264ad9d517ce54381ca6daaaa584ee5b

**Pull request closed without merging**
